### ISSUE TITLE
Introduce Bridges

### ISSUE THREAD

**Issue by ksmonkey123** [WaDosCh/SimTrack#12]
~~If #11 introduces water, maybe~~ Allow creation of special straight tracks (without curves, switching or crossing, but with signals) to build bridges. If #9 introduces money, bridges should be much more expensive to build.

**Comment by ksmonkey123** [comment]
Easy to do, just need support for composite tiles.

**Comment by judos** [comment]
Which tracks are allowed as bridges could be level dependent. Would require maybe some ruleset in the game to define what actions are allowed and which ones aren't.
Renderer could for now just add a filled rect below straight tracks.

**Comment by ksmonkey123** [comment]
Can be done. Maybe we could also make allowed tracks dependent on the level (for every tile). This could also be done in combination with #65
