### ISSUE TITLE
introduce ingame menu

### ISSUE THREAD

**Issue by judos** [WaDosCh/SimTrack#28]
pressing esc usually drops the tool. This could be generalized. E.g. not the tool has the logic what esc means but the Editor/InterfaceController defines that esc means 'drop tool'.
If the player has no tool active, another esc could mean open the game menu (save,load,options,quit).

**Comment by ksmonkey123** [comment]
won't work everywhere, as some tools may need to override the escape functionality for tool-internal sub-menus. It would probably be safer to introduce something like a `AutoClosingTool` parent class that handles the escape button by default. This way basic tools could extend that class for escape behaviour, but more specialized tools can still define their closing behaviour themselves.

**Comment by ksmonkey123** [comment]
also: the player never has "no tool". The default tool is the `FreeHandTool`. Therefore a game menu functionality could be introduced through the `FreeHandTool` delegating the menu to the controller when `ESC` is pressed.

**Comment by judos** [comment]
Good points ^^ Actually that makes it easier to implement menus. They can be internally implemented like the normal tools.
With "no tool" i meant the FreeHandTool actually. I know it's better not to have a null value there and do some hacky stuff :)

**Comment by judos** [comment]
primitive ingame menu is implemented with the options: resume, save, load, quit.
Save and load do nothing for the moment.
![grafik](https://user-images.githubusercontent.com/5525810/35532562-f337e3e0-053a-11e8-9e97-ca716d120ad1.png)
