### ISSUE TITLE
Rework Interface Based Architecture

### ISSUE THREAD

**Issue by ksmonkey123** [WaDosCh/SimTrack#44]
### Current Behaviour
Many of the virtually unique types (GameController, ViewPort, Model, ...) are abstracted away behind interfaces in an attempt to reduce coupling. However during the last 2 months more coupling was required making these interfaces very hard to work with. (e.g. every new helper method on the Model has to be added to IModel as well)

### Requested Behaviour
Remove the interfaces for mayor types (GameController, ViewPort, Model, ...) and reference these classes directly. Additionally the old interface naming scheme (`IXxx`) could be changed to omit the leading `I` as after removing the interfaces from interface-class-pairs there will no longer be any naming collisions and prefixing interface names with `I` is discouraged.

**Comment by judos** [comment]
We could have a look at this in a pair-programming session next monday?
