### ISSUE TITLE
Train Spawning and Despawning

### ISSUE THREAD

**Issue by ksmonkey123** [WaDosCh/SimTrack#48]
### Current Behaviour
Trains spawn only on `F4` and do not despawn when they reach a destination.

### Requested Behaviour
 - [x] Trains should spawn on their own.
 - [x] Trains should enter the destination tile completely and despawn once the last waggon has left the map.
   - this may require the addition of virtual tiles beyond the destination or something similar. This could even be handled on the model level where *synthetic* tiles could be provided that allow the train to *drive straight off the edge* of the destination

**Comment by ksmonkey123** [comment]
This could work, however this behaviour is only acceptable if the train leaves a destination tile. If the train reaches a dead end on the map (player destroyed the tile in front of the train) the train must stop, discard its path and wait for a new valid path to be reached.

Also the train must know the position of the last waggon to be able to release tiles behind itself to support #47

**Comment by judos** [comment]
The train can ask the current tile whether it is a destinationTile. If yes continue moving and leaving the map, otherwise pull the brakes...
