### ISSUE TITLE
Provide Performance Profiler

### ISSUE THREAD

**Issue by ksmonkey123** [WaDosCh/SimTrack#52]
### Requested Behaviour
An In-Game Profiler measuring the CPU cost for different Renderers and Tickers would allow a very fine-grained performance analysis on a high level. The profiler could be integrated into the base `Controller` class.

The current implementation, where the `Scene<T>` instances provide ordered lists of required `BaseRenderer<T>` and `BaseTicker<T>` instances to the `Controller` allows the `Controller` to directly measure the runtimes for each of these instances.

Additionally the profiler could provide some VM information (i.e. memory usage)

**Comment by judos** [comment]
Note: I would put a very low priority on this as we don't need to worry about performence yet.

**Comment by ksmonkey123** [comment]
I disagree. I have observed in multiple cases where the "*we can worry about that later*"-attitude lead to a situation where at some point a profiler needed to be added in after performance became an issue. The new scene system allows for a simple profiler to be added in with minimal effort (<1h) and without any impact on the rest of the code. I will therefore continue to persue it.
