### ISSUE TITLE
Main menu

### ISSUE THREAD

**Issue by judos** [WaDosCh/SimTrack#54]
Add a main game menu

- [x]  ability to load different game scenarios / predefined list of maps
- [x] options menu 
- [x] load save

**Comment by ksmonkey123** [comment]
options not in main menu, button exists, but options menu should be implemented probably as another scene

**Comment by ksmonkey123** [comment]
commit fea97d18083f4bb7ae0382f5071dccc1b7c85256 finishes off a basic game menu. More complex functionality needs to be implemented in separate scenes. Issues have been created for these items to be completed separately. Therefore I consider this Issue to be completed.
