### ISSUE TITLE
allowed tracks

### ISSUE THREAD

**Issue by judos** [WaDosCh/SimTrack#56]
### Current Behaviour

This track is not allowed to build:
![screenshot 2018-02-22 18 50 36](https://user-images.githubusercontent.com/5525810/36555113-65f619aa-1801-11e8-9592-3e5e680838cd.png)

### Question

Should we allow it? Should we allow all track combinations which are a subset of another track combination?
![screenshot 2018-02-22 18 54 01](https://user-images.githubusercontent.com/5525810/36555290-c997f366-1801-11e8-964b-5b470746fce6.png)

**Comment by ksmonkey123** [comment]
1. Not found IRL
2. potentially confusing due to block sharing.

Won't add them
