### ISSUE TITLE
calculate reachability sets for any given edge

### ISSUE THREAD

**Issue by ksmonkey123** [WaDosCh/SimTrack#6]
for a given (directed) edge determine which destination tiles can be reached. Probably construct a directed graph representing the complete rail network.

Depends on #4

**Comment by ksmonkey123** [comment]
explanation: the idea here is to be able to determine for each inbound connection (spawn point) which outbound connections (despawn points) are reachable such that no trains are spawned without paths to their destination. It could of course be argued that spawning unserviceable trains would be an additional gameplay challenge.

@judos what do you think?

**Comment by judos** [comment]
I think it's closed.
