### ISSUE TITLE
Trains not rendered centred unless horizontal

### ISSUE THREAD

**Issue by ksmonkey123** [WaDosCh/SimTrack#61]
Whenever a train is not in a horizontal position, the elements are not rendered centred on the tracks:

<img width="457" alt="screen shot 2018-02-23 at 21 54 39" src="https://user-images.githubusercontent.com/5485109/36616527-6985c122-18e4-11e8-98d9-784cf0506ae6.png">
<img width="344" alt="screen shot 2018-02-23 at 21 54 16" src="https://user-images.githubusercontent.com/5485109/36616528-69a368ee-18e4-11e8-91f7-e45a08ca517e.png">

**Comment by judos** [comment]
looks offset something like 3 pixel. Did you take the screenshot after pulling the updates to render tracks nicer? The straight track in the second image on the right below the wagon seems cut a bit again.
Maybe the issue also has something to do with the float Y-offset between tiles...

**Comment by ksmonkey123** [comment]
I believe to have used a clean build of the latest revision on the `master` branch at the time of opening the ticket. I will verify it tonight

**Comment by ksmonkey123** [comment]
Could not reproduce with a clean build of commit f531d7bf24d9eb80b873ece9de899cdd97426093
