### ISSUE TITLE
rule-sets for model editing

### ISSUE THREAD

**Issue by ksmonkey123** [WaDosCh/SimTrack#71]
### Current Behaviour
Different Placement and edit rules are hard-coded in the model.

### Requested Behaviour
The different base operations should be identified and a rule-set should be created allowing for fine-grained control over the actions. The model itself should delegate rule checking to the rule-set and simply execute the requested operation if the rule-set considers it to be OK. This allows for the definition of special rules for scenarios or difficulty settings for custom games. These rules should control:

- [ ] Legal Track Tiles (also covers tile merging)
- [ ] Legal Signal Positions (e.g. if signals can be put onto bridges)
- [ ] Legal Tile Combinations (e.g. where can bridges be built, what tiles can be built as bridges)

**Comment by judos** [comment]
Also edit base model for tile. E.g. properties for any tile:
terrain: enum?
track: {
  station: boolean,
  trackPaths: [ path ]
}
...
