### ISSUE TITLE
Introduce Trains

### ISSUE THREAD

**Issue by ksmonkey123** [WaDosCh/SimTrack#8]
- [x] add method to calculate exact position on a tilepath depending on one variable
- [x] draw train as circle on the exact position to make movement realistic
- [x] add class for configuration of the locomotive properties (axis position on the image)
- [x] position locomotive picture according to axis property + calculated position value
- [x] angle locomotive picture according to second axis property + calculated position value

Initially maybe simple "1-tile" trains.

Depends on #4 (#6 ?) #7

**Comment by judos** [comment]
initial version with simple graphics and rudimentary movement is done

**Comment by judos** [comment]
![grafik](https://user-images.githubusercontent.com/5525810/35544501-f29ec838-056a-11e8-826d-bf082b7e3b21.png)

**Comment by ksmonkey123** [comment]
please only close once movement is completed

**Comment by judos** [comment]
- [ ] add method to calculate exact position on a tilepath depending on one variable
- [ ] draw train as circle on the exact position to make movement realistic
- [ ] add class for configuration of the locomotive properties (axis position on the image)
- [ ] position locomotive picture according to axis property + calculated position value
- [ ] angle locomotive picture according to second axis property + calculated position value

**Comment by judos** [comment]
Done. We even have a first wagon configuration.

See:
![2 trains driving around on tracks](https://raw.githubusercontent.com/WaDosCh/SimTrack/master/screenshots/simtrack3%20first%20train%20compositions.PNG)
