### ISSUE TITLE
use proper graphics framework

### ISSUE THREAD

**Issue by judos** [WaDosCh/SimTrack#82]
e.g. https://www.lwjgl.org/#learn-more
or processing library: https://processing.org/

advantage of lwjgl is it also provides easy access to audio functionality

**Comment by ksmonkey123** [comment]
no OpenGL framework may be used if Mac compatibility should be preserved as apple has deprecated OpenGL and my tests with java + LWJGL and with java + JOGL already displayed compatibility issues that make proper operation completely impossible

**Comment by judos** [comment]
hmm not sure but processing seems also backed by opengl not sure though.
Any propositions in that case?

**Comment by ksmonkey123** [comment]
I could run some tests. processing may have patched the IO-Event issues present in JOGL and LWJGL

**Comment by judos** [comment]
Sounds good, it would be cool to have simple images in the game for the tiles so it looks already a lot better :)
