### ISSUE TITLE
Introduce Finances

### ISSUE THREAD

**Issue by ksmonkey123** [WaDosCh/SimTrack#9]
- [x] Player has starting money
- [x] Every track get's assigned a cost
- [x] Building tracks has a cost
- [x] removing tracks has a cost
- [x] Any train that reaches its destination earns money proportional to the distance (carthesian distance)
~~Trains that need to despawn due to a lack of a possible route give a penalty~~ (won't fix, trains should not despawn, looks bad in a simulation game imo)
- [x] construction only possible if `budget >= cost`
- [ ] penalties can be negative

**Comment by judos** [comment]
Any concrete ideas here? We could add a checklist with what we want.
Maybe:
[ ] Player has starting money (e.g. 10 M€ or 1000 Bitcoin :D)
[ ] Every track get's assigned a specific cost amount
[ ] Building / removing tracks cost a specific amount

**Comment by ksmonkey123** [comment]
Building / Modifying tracks should cost money, routing trains to destinations should earn you some money. needs to be properly balanced

**Comment by judos** [comment]
I will adapt your original comment such that we have a checklist ^^
